/* 

MIDI to joy.
Based on GENERIC MIDI APP V.0.6 by genmce and contributors.

Edit the "VARIBLES TO SET @ STARTUP" section.

MidiRules.ahk contains the logic that maps from MIDI controllers to VJoy.


Sections with !!!!!!!!!!!!!!!!!!!! - don't edit between these, unless you know what you are doing (uykwyad) !  

Sections with ++++++++++++++++++++ Edit between these marks. You won't break it, I don't think???
 
*/
 
#Persistent
#SingleInstance, force
#NoEnv
#UseHook
#MaxThreadsBuffer, On
#MaxHotkeysPerInterval, 500
#MaxThreadsPerHotkey, 4
SetTitleMatchMode 2
SendMode Input
SetControlDelay -1
DetectHiddenWindows On
SetMouseDelay -1
SetWinDelay -1
SetWorkingDir %A_ScriptDir%

global imgdir := % A_ScriptDir "\img\"
#Include %A_ScriptDir%\lib\CommonFunctions.ahk 

if A_OSVersion in WIN_NT4,WIN_95,WIN_98,WIN_ME  ; if not xp or 2000 quit
{
	MsgBox This script requires Windows 2000/XP or later.
	ExitApp
}
apptitle = MidiToMacro
readini()								; load values from the ini file, via the readini function - see Midi_under_the_hood.ahk file
gosub, MidiPortRefresh				; used to refresh the input and output port lists - see Midi_under_the_hood.ahk file
port_test(numports,numports2)		; test the ports - check for valid ports? - see Midi_under_the_hood.ahk file
gosub, midiin_go						; opens the midi input port listening routine see Midi_under_the_hood.ahk file

;; HOTKEYS
Hotkey, +!Esc, Restart
return


#Include %A_ScriptDir%\lib\MidiInAndGuiMonitor.ahk	; this file contains: the function to parse midi message into parts we can work with and a midi monitor.
#Include %A_ScriptDir%\lib\MidiRules.ahk				; this file contains: Rules for manipulating midi input then sending modified midi output.
#Include %A_ScriptDir%\lib\MidiUnderTheHood.ahk		; this file contains: (DO NOT EDIT THIS FILE) all the dialogs to set up midi ports and midi message handling.

Restart:
	Critical
	Reload
return